Repository Kusitms-28th-Meetup-D/backend, pull requests merged in 2023-10, with the labels that each got.

#2 이슈, pr 템플릿 생성
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: feat, 진영🐧

#4 프로젝트 초기 설정
  build.gradle
  src/main/java/com/kusithm/meetupd/common/config/SwaggerConfig.java
  src/main/java/com/kusithm/meetupd/common/config/TimezoneConfig.java
  src/main/java/com/kusithm/meetupd/common/config/WebConfig.java
  src/main/java/com/kusithm/meetupd/common/controller/HealthCheckAPI.java
  src/main/java/com/kusithm/meetupd/common/dto/SuccessResponse.java
  src/main/java/com/kusithm/meetupd/common/dto/code/SuccessCode.java
  src/main/java/com/kusithm/meetupd/common/entity/BaseEntity.java
  src/main/java/com/kusithm/meetupd/common/error/ApplicationException.java
  src/main/java/com/kusithm/meetupd/common/error/DuplicateException.java
  src/main/java/com/kusithm/meetupd/common/error/EntityNotFoundException.java
  src/main/java/com/kusithm/meetupd/common/error/ErrorCode.java
  src/main/java/com/kusithm/meetupd/common/error/dto/ErrorResponse.java
  src/main/java/com/kusithm/meetupd/common/error/handler/ApplicationExceptionHandler.java
  src/main/java/com/kusithm/meetupd/domain/sample/controller/SampleController.java
  src/main/java/com/kusithm/meetupd/domain/sample/dto/request/CreateSampleRequestDto.java
  src/main/java/com/kusithm/meetupd/domain/sample/dto/response/CreateSampleResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/sample/entity/Sample.java
  src/main/java/com/kusithm/meetupd/domain/sample/repository/SampleRepository.java
  src/main/java/com/kusithm/meetupd/domain/sample/service/SampleService.java
Labels: feat

#8 카카오 소셜로그인, 시큐리티를 통한 인가 인증
  build.gradle
  src/main/java/com/kusithm/meetupd/common/auth/AuthConstants.java
  src/main/java/com/kusithm/meetupd/common/auth/CustomAuthenticationEntryPoint.java
  src/main/java/com/kusithm/meetupd/common/auth/ExceptionHandlerFilter.java
  src/main/java/com/kusithm/meetupd/common/auth/JwtAuthenticationFilter.java
  src/main/java/com/kusithm/meetupd/common/auth/UserId.java
  src/main/java/com/kusithm/meetupd/common/auth/UserIdArgumentResolver.java
  src/main/java/com/kusithm/meetupd/common/config/FeignClientConfig.java
  src/main/java/com/kusithm/meetupd/common/config/SecurityConfig.java
  src/main/java/com/kusithm/meetupd/common/config/WebConfig.java
  src/main/java/com/kusithm/meetupd/common/dto/code/SuccessCode.java
  src/main/java/com/kusithm/meetupd/common/error/ApplicationException.java
  src/main/java/com/kusithm/meetupd/common/error/ErrorCode.java
  src/main/java/com/kusithm/meetupd/common/error/ForbiddenException.java
  src/main/java/com/kusithm/meetupd/common/error/UnauthorizedException.java
  src/main/java/com/kusithm/meetupd/common/error/dto/ErrorResponse.java
  src/main/java/com/kusithm/meetupd/common/error/handler/ApplicationExceptionHandler.java
  src/main/java/com/kusithm/meetupd/common/jwt/TokenProvider.java
  src/main/java/com/kusithm/meetupd/common/jwt/dto/Token.java
  src/main/java/com/kusithm/meetupd/common/redis/entity/RefreshToken.java
  src/main/java/com/kusithm/meetupd/common/redis/repository/RefreshTokenRepository.java
  src/main/java/com/kusithm/meetupd/domain/auth/controller/AuthController.java
  src/main/java/com/kusithm/meetupd/domain/auth/dto/request/KakaoLoginRequestDto.java
  src/main/java/com/kusithm/meetupd/domain/auth/dto/request/KakaoRegisterRequestDto.java
  src/main/java/com/kusithm/meetupd/domain/auth/dto/request/ReissueRequestDto.java
  src/main/java/com/kusithm/meetupd/domain/auth/dto/response/KakaoLoginResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/auth/dto/response/KakaoRegisterResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/auth/dto/response/ReissueResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/auth/kakao/KakaoAccessToken.java
  src/main/java/com/kusithm/meetupd/domain/auth/kakao/KakaoFeignClient.java
  src/main/java/com/kusithm/meetupd/domain/auth/kakao/dto/KakaoGetIdResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/auth/kakao/dto/KakaoGetUserInfoResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/auth/service/AuthService.java
  src/main/java/com/kusithm/meetupd/domain/user/controller/UserController.java
  src/main/java/com/kusithm/meetupd/domain/user/dto/response/UserCheckResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/User.java
  src/main/java/com/kusithm/meetupd/domain/user/repository/UserRepository.java
  src/main/java/com/kusithm/meetupd/domain/user/service/UserService.java
Labels: feat, 진영🐧

#12 프로젝트 내 mongodb 연결
  build.gradle
  src/main/java/com/kusithm/meetupd/common/config/JpaConfig.java
  src/main/java/com/kusithm/meetupd/common/config/MongoDbConfig.java
  src/main/java/com/kusithm/meetupd/domain/auth/service/AuthService.java
  src/main/java/com/kusithm/meetupd/domain/sample/mysql/SampleRepository.java
  src/main/java/com/kusithm/meetupd/domain/sample/service/SampleService.java
  src/main/java/com/kusithm/meetupd/domain/user/mysql/UserRepository.java
  src/main/java/com/kusithm/meetupd/domain/user/service/UserService.java
Labels: feat, 진영🐧

#13 S3 연동 및 이미지 업로드
  build.gradle
  src/main/java/com/kusithm/meetupd/common/config/S3Config.java
  src/main/java/com/kusithm/meetupd/common/config/SecurityConfig.java
  src/main/java/com/kusithm/meetupd/common/error/ErrorCode.java
  src/main/java/com/kusithm/meetupd/common/error/FileUploadFailedException.java
  src/main/java/com/kusithm/meetupd/domain/fileUpload/controller/S3FileUploadController.java
  src/main/java/com/kusithm/meetupd/domain/fileUpload/dto/response/FileUploadResponse.java
  src/main/java/com/kusithm/meetupd/domain/fileUpload/entity/Image.java
  src/main/java/com/kusithm/meetupd/domain/fileUpload/mysql/ImageRepository.java
  src/main/java/com/kusithm/meetupd/domain/fileUpload/service/AwsS3Service.java
  src/main/java/com/kusithm/meetupd/domain/sample/service/SampleService.java
Labels: feat, 민정🦫

#18 [fix] cors 포트 추가
  src/main/java/com/kusithm/meetupd/common/config/WebConfig.java
Labels: fix, 진영🐧

#16 Feature/15 user
  src/main/java/com/kusithm/meetupd/domain/grade/entity/Grade.java
  src/main/java/com/kusithm/meetupd/domain/grade/entity/TYPE.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/Carrer.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/GENDER.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/Major.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/Skill.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/Task.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/User.java
Labels: feat, refactor, 민정🦫
