Repository Kusitms-28th-Meetup-D/backend, pull requests merged in 2023-11, with the labels that each got.

#20 공모전 도메인 세팅 및 카테고리/전체 조회 API 작성
  src/main/java/com/kusithm/meetupd/common/config/SecurityConfig.java
  src/main/java/com/kusithm/meetupd/common/dto/SuccessResponse.java
  src/main/java/com/kusithm/meetupd/common/error/EnumNotFoundException.java
  src/main/java/com/kusithm/meetupd/common/error/ErrorCode.java
  src/main/java/com/kusithm/meetupd/domain/contest/controller/ContestController.java
  src/main/java/com/kusithm/meetupd/domain/contest/converter/ContestTypeConverter.java
  src/main/java/com/kusithm/meetupd/domain/contest/dto/response/FindContestsResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/contest/entity/Contest.java
  src/main/java/com/kusithm/meetupd/domain/contest/entity/ContestType.java
  src/main/java/com/kusithm/meetupd/domain/contest/mongo/ContestRepository.java
  src/main/java/com/kusithm/meetupd/domain/contest/service/ContestService.java
Labels: feat, 진영🐧

#27 추천사 도메인 개발
  src/main/java/com/kusithm/meetupd/common/auth/JwtAuthenticationFilter.java
  src/main/java/com/kusithm/meetupd/common/config/MongoDbConfig.java
  src/main/java/com/kusithm/meetupd/common/error/ConflictException.java
  src/main/java/com/kusithm/meetupd/common/error/DuplicateException.java
  src/main/java/com/kusithm/meetupd/common/error/ErrorCode.java
  src/main/java/com/kusithm/meetupd/domain/auth/service/AuthService.java
  src/main/java/com/kusithm/meetupd/domain/review/controller/ReviewController.java
  src/main/java/com/kusithm/meetupd/domain/review/dto/request/UploadReviewRequestDto.java
  src/main/java/com/kusithm/meetupd/domain/review/dto/response/GetIsUserReviewTeamResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/review/dto/response/GetUserReviewResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/review/dto/response/UploadReviewResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/review/entity/Review.java
  src/main/java/com/kusithm/meetupd/domain/review/entity/UserReviewedTeam.java
  src/main/java/com/kusithm/meetupd/domain/review/entity/WaitReview.java
  src/main/java/com/kusithm/meetupd/domain/review/entity/inner/ReviewChoice.java
  src/main/java/com/kusithm/meetupd/domain/review/entity/inner/ReviewComment.java
  src/main/java/com/kusithm/meetupd/domain/review/entity/inner/ReviewTeamCulture.java
  src/main/java/com/kusithm/meetupd/domain/review/entity/inner/ReviewWorkMethod.java
  src/main/java/com/kusithm/meetupd/domain/review/entity/inner/SelectKeyword.java
  src/main/java/com/kusithm/meetupd/domain/review/entity/inner/SelectTeamCulture.java
  src/main/java/com/kusithm/meetupd/domain/review/entity/inner/SelectWorkMethod.java
  src/main/java/com/kusithm/meetupd/domain/review/entity/type/ChoiceCountType.java
  src/main/java/com/kusithm/meetupd/domain/review/entity/type/TeamCultureType.java
  src/main/java/com/kusithm/meetupd/domain/review/entity/type/WorkMethodType.java
  src/main/java/com/kusithm/meetupd/domain/review/mongo/ReviewRepository.java
  src/main/java/com/kusithm/meetupd/domain/review/mongo/WaitReviewRepository.java
  src/main/java/com/kusithm/meetupd/domain/review/mysql/UserReviewedTeamRepository.java
  src/main/java/com/kusithm/meetupd/domain/review/service/ReviewService.java
  src/main/java/com/kusithm/meetupd/domain/review/util/ListComparatorKeywordCount.java
  src/main/java/com/kusithm/meetupd/domain/sample/service/SampleService.java
Labels: feat, 진영🐧

#29 공모전 조회 API
  src/main/java/com/kusithm/meetupd/common/auth/JwtAuthenticationFilter.java
  src/main/java/com/kusithm/meetupd/domain/contest/controller/ContestController.java
  src/main/java/com/kusithm/meetupd/domain/contest/dto/response/FindContestsResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/contest/mongo/ContestRepository.java
  src/main/java/com/kusithm/meetupd/domain/contest/service/ContestService.java
Labels: feat, 진영🐧

#31 리뷰 등록 시 이메일 전송
  src/main/java/com/kusithm/meetupd/domain/review/aws/AWSFeignClient.java
  src/main/java/com/kusithm/meetupd/domain/review/aws/dto/request/SendEmailByAWSFeignRequestDto.java
  src/main/java/com/kusithm/meetupd/domain/review/service/ReviewService.java
Labels: feat, 진영🐧

#34 현재 모집중인 팀 조회 api
  src/main/java/com/kusithm/meetupd/common/auth/JwtAuthenticationFilter.java
  src/main/java/com/kusithm/meetupd/domain/team/controller/TeamController.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/request/PageDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/PageResponseDTO.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/RecruitingContestTeamResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/RecruitingTeamResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/TeamResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/entity/Team.java
  src/main/java/com/kusithm/meetupd/domain/team/entity/TeamProgressType.java
  src/main/java/com/kusithm/meetupd/domain/team/entity/TeamUser.java
  src/main/java/com/kusithm/meetupd/domain/team/entity/TeamUserRoleType.java
  src/main/java/com/kusithm/meetupd/domain/team/mysql/TeamRepository.java
  src/main/java/com/kusithm/meetupd/domain/team/mysql/TeamUserRepository.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/LocationType.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/User.java
Labels: feat, 민정🦫

#36 공모전 상세 조회
  src/main/java/com/kusithm/meetupd/common/auth/JwtAuthenticationFilter.java
  src/main/java/com/kusithm/meetupd/domain/contest/controller/ContestController.java
  src/main/java/com/kusithm/meetupd/domain/contest/dto/response/GetContestDetailInfoResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/contest/entity/Contest.java
  src/main/java/com/kusithm/meetupd/domain/contest/service/ContestService.java
Labels: feat, 진영🐧

#39 회원가입 API 수정
  src/main/java/com/kusithm/meetupd/domain/auth/dto/request/KakaoRegisterRequestDto.java
  src/main/java/com/kusithm/meetupd/domain/auth/kakao/dto/KakaoGetUserInfoResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/auth/service/AuthService.java
  src/main/java/com/kusithm/meetupd/domain/user/dto/UserMypageResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/Location.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/Major.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/Task.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/User.java
Labels: feat, 진영🐧

#41 티켓 개수 조회 및 구매 API 추가
  src/main/java/com/kusithm/meetupd/domain/user/controller/UserController.java
  src/main/java/com/kusithm/meetupd/domain/user/dto/request/BuyUserTicketRequestDto.java
  src/main/java/com/kusithm/meetupd/domain/user/dto/response/UserTicketCountResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/Ticket.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/User.java
  src/main/java/com/kusithm/meetupd/domain/user/service/UserService.java
Labels: feat, 진영🐧

#46 [feat]공모전 상세 조회에서 모집중인 팀 조회 api
  src/main/java/com/kusithm/meetupd/common/auth/JwtAuthenticationFilter.java
  src/main/java/com/kusithm/meetupd/domain/team/controller/TeamController.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/RecruitingContestTeamResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/ResponseTeamLeaderDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/ResponseTeamMemeberDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/TeamDetailResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/entity/Team.java
  src/main/java/com/kusithm/meetupd/domain/team/mysql/TeamRepository.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
Labels: feat, refactor, 민정🦫

#45 비회원 추천사 작성 및 비회원 추천사 작성 여부 확인 API
  src/main/java/com/kusithm/meetupd/common/auth/JwtAuthenticationFilter.java
  src/main/java/com/kusithm/meetupd/common/error/ErrorCode.java
  src/main/java/com/kusithm/meetupd/domain/review/controller/ReviewController.java
  src/main/java/com/kusithm/meetupd/domain/review/dto/request/NonUserReviewRequestDto.java
  src/main/java/com/kusithm/meetupd/domain/review/dto/response/CheckUserReviewedByNonUserResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/review/entity/NonUserReview.java
  src/main/java/com/kusithm/meetupd/domain/review/entity/WaitReview.java
  src/main/java/com/kusithm/meetupd/domain/review/mongo/NonUserReviewRepository.java
  src/main/java/com/kusithm/meetupd/domain/review/service/ReviewService.java
  src/main/java/com/kusithm/meetupd/domain/user/service/UserService.java
Labels: feat, 진영🐧

#53 [refactor] login 응답 정보 수정
  src/main/java/com/kusithm/meetupd/domain/auth/dto/response/KakaoLoginResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/auth/service/AuthService.java
  src/main/java/com/kusithm/meetupd/domain/team/controller/TeamController.java
Labels: refactor, 민정🦫

#49 기존 추천사 작성 및 작성 여부 조회 API 인증 필요 여부 변경
  src/main/java/com/kusithm/meetupd/common/auth/JwtAuthenticationFilter.java
  src/main/java/com/kusithm/meetupd/domain/review/controller/ReviewController.java
  src/main/java/com/kusithm/meetupd/domain/review/dto/request/UploadReviewRequestDto.java
Labels: fix, 민정🦫

#55 [feat] 공모전 팀 등록 api
  src/main/java/com/kusithm/meetupd/common/auth/JwtAuthenticationFilter.java
  src/main/java/com/kusithm/meetupd/common/error/ErrorCode.java
  src/main/java/com/kusithm/meetupd/domain/team/controller/TeamController.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/request/RequestCreateTeamDto.java
  src/main/java/com/kusithm/meetupd/domain/team/entity/Team.java
  src/main/java/com/kusithm/meetupd/domain/team/entity/TeamUser.java
  src/main/java/com/kusithm/meetupd/domain/team/mysql/TeamUserRepository.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/Location.java
Labels: feat, 민정🦫

#57 유저 프로필 추가정보 추가하는 API
  src/main/java/com/kusithm/meetupd/domain/user/controller/UserController.java
  src/main/java/com/kusithm/meetupd/domain/user/dto/request/UserProfileUpdateRequestDto.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/Award.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/Certificate.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/Internship.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/Task.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/Tool.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/User.java
  src/main/java/com/kusithm/meetupd/domain/user/service/UserService.java
Labels: feat, 진영🐧

#61 공모전 상세 정보 보는 응답값 데이터 추가
  src/main/java/com/kusithm/meetupd/domain/contest/controller/ContestController.java
  src/main/java/com/kusithm/meetupd/domain/contest/dto/response/GetContestDetailInfoResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/contest/mongo/ContestRepository.java
  src/main/java/com/kusithm/meetupd/domain/contest/service/ContestService.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
Labels: feat, 진영🐧

#62 [feat]팀 상세조회 api
  src/main/java/com/kusithm/meetupd/common/auth/JwtAuthenticationFilter.java
  src/main/java/com/kusithm/meetupd/common/dto/code/SuccessCode.java
  src/main/java/com/kusithm/meetupd/common/error/ErrorCode.java
  src/main/java/com/kusithm/meetupd/domain/team/controller/TeamController.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/TestDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/request/RequestChangeRoleDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/request/RequestCreateTeamDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/RecruitingContestTeamResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/TeamDetailResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/entity/TeamUser.java
  src/main/java/com/kusithm/meetupd/domain/team/mysql/TeamUserRepository.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
Labels: feat, 민정🦫

#58 [feat] 팀 지원,팀원 상태 변경 api
  src/main/java/com/kusithm/meetupd/common/error/ErrorCode.java
  src/main/java/com/kusithm/meetupd/domain/team/controller/TeamController.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/request/RequestChangeRoleDto.java
  src/main/java/com/kusithm/meetupd/domain/team/mysql/TeamUserRepository.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
Labels: feat, 민정🦫

#67 [fix] 팀 상세조회 whitelist 수정
  src/main/java/com/kusithm/meetupd/common/auth/JwtAuthenticationFilter.java
Labels: fix

#64 cors 문제 해결하기
  src/main/java/com/kusithm/meetupd/common/config/CorsConfig.java
  src/main/java/com/kusithm/meetupd/common/config/SecurityConfig.java
  src/main/java/com/kusithm/meetupd/common/config/WebConfig.java
Labels: feat, fix, 진영🐧

#69 [fix] 마이페이지 유저 종보 조회 수정
  src/main/java/com/kusithm/meetupd/common/auth/JwtAuthenticationFilter.java
  src/main/java/com/kusithm/meetupd/domain/user/controller/UserController.java
Labels: fix, 민정🦫

#71 [fix] mypage url 변경
  src/main/java/com/kusithm/meetupd/domain/user/controller/UserController.java
Labels: fix, 민정🦫

#73 이메일 보내는 서비스 추가
  .github/workflows/cicd.yml
  build.gradle
  src/main/java/com/kusithm/meetupd/MeetupDApplication.java
  src/main/java/com/kusithm/meetupd/common/config/AsyncConfig.java
  src/main/java/com/kusithm/meetupd/domain/email/service/EmailService.java
  src/main/resources/templates/join-team-mail.html
  src/main/resources/templates/new-review-mail.html
Labels: feat, 진영🐧

#75 유저 마이페이지 정보 불러오는 API Resonse 수정
  src/main/java/com/kusithm/meetupd/common/auth/JwtAuthenticationFilter.java
  src/main/java/com/kusithm/meetupd/domain/user/controller/UserController.java
Labels: fix, 진영🐧

#77 [feat]내가 오픈한 팀 api
  src/main/java/com/kusithm/meetupd/common/auth/JwtAuthenticationFilter.java
  src/main/java/com/kusithm/meetupd/common/error/ErrorCode.java
  src/main/java/com/kusithm/meetupd/domain/team/controller/TeamController.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/TeamIOpenedResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/request/RequestCreateTeamDto.java
  src/main/java/com/kusithm/meetupd/domain/team/entity/Team.java
  src/main/java/com/kusithm/meetupd/domain/team/mysql/TeamRepository.java
  src/main/java/com/kusithm/meetupd/domain/team/mysql/TeamUserRepository.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
Labels: feat, 민정🦫

#79 [refactor] 내가오픈한팀 조회 api 수정
  src/main/java/com/kusithm/meetupd/domain/team/mysql/TeamUserRepository.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
Labels: feat, 민정🦫

#78 리뷰 작성 시 이메일 전송
  src/main/java/com/kusithm/meetupd/domain/review/controller/ReviewController.java
  src/main/java/com/kusithm/meetupd/domain/review/service/ReviewService.java
Labels: feat, 진영🐧

#85 [feat] 팀 모집 취소,팀 모집 중 -> 모집 완료로 상태 변경,팀 지원 취소하기,내가 오픈한 팀,내가 지원한 팀,활동중…
  src/main/java/com/kusithm/meetupd/common/error/ErrorCode.java
  src/main/java/com/kusithm/meetupd/domain/review/dto/request/UpdateTeamProgressRecruitmentRequestDto.java
  src/main/java/com/kusithm/meetupd/domain/team/controller/TeamController.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/TeamIOpenedResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/request/ApplyTeamRequestDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/request/TeamProceedResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/TeamDetailResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/TeamIWorkedResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/TeamIappliedResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/entity/Team.java
  src/main/java/com/kusithm/meetupd/domain/team/entity/TeamUserRoleType.java
  src/main/java/com/kusithm/meetupd/domain/team/mysql/TeamUserRepository.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
Labels: feat, 민정🦫

#87 [refactor] endDate수정
  src/main/java/com/kusithm/meetupd/domain/team/dto/request/TeamProceedResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/TeamDetailResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/TeamIWorkedResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/TeamIappliedResponseDto.java
Labels: refactor, 민정🦫

#88 [fix] 객관식 리뷰 문항 변경
  src/main/java/com/kusithm/meetupd/domain/review/entity/type/ChoiceCountType.java
Labels: fix, 진영🐧

#89 [remove] 유저 리뷰 정보 가져오는 API 권한 필요 하도록 whiteList에서 제거
  src/main/java/com/kusithm/meetupd/common/auth/JwtAuthenticationFilter.java
Labels: remove, 진영🐧

#92 유저 계정정보 변경 API
  src/main/java/com/kusithm/meetupd/domain/auth/service/AuthService.java
  src/main/java/com/kusithm/meetupd/domain/team/controller/TeamController.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/request/RequestCreateTeamDto.java
  src/main/java/com/kusithm/meetupd/domain/team/entity/Team.java
  src/main/java/com/kusithm/meetupd/domain/team/entity/TeamLocation.java
  src/main/java/com/kusithm/meetupd/domain/team/entity/TeamUser.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
  src/main/java/com/kusithm/meetupd/domain/user/controller/UserController.java
  src/main/java/com/kusithm/meetupd/domain/user/dto/request/UpdateUserAccountInfoRequestDto.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/Major.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/Task.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/User.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/UserLocation.java
  src/main/java/com/kusithm/meetupd/domain/user/service/UserService.java
Labels: feat, 진영🐧

#95 [feat] 활동중인 팀 api
  src/main/java/com/kusithm/meetupd/domain/team/controller/TeamController.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/request/TeamProceedResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/TeamIappliedResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/mysql/TeamUserRepository.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
Labels: feat, 민정🦫

#97 [feat] 프론트 배포 url cors 추가
  src/main/java/com/kusithm/meetupd/common/config/CorsConfig.java
  src/main/java/com/kusithm/meetupd/common/config/WebConfig.java
Labels: feat, 진영🐧

#99 팀 활동 완료일 지났으면 상태 변경해주기
  src/main/java/com/kusithm/meetupd/MeetupDApplication.java
  src/main/java/com/kusithm/meetupd/common/config/SchedulerConfig.java
  src/main/java/com/kusithm/meetupd/domain/email/service/EmailService.java
  src/main/java/com/kusithm/meetupd/domain/team/mysql/TeamRepository.java
  src/main/java/com/kusithm/meetupd/domain/team/mysql/TeamUserRepository.java
  src/main/java/com/kusithm/meetupd/domain/team/scheduler/TeamScheduler.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
  src/main/resources/templates/team-review-date-end-mail.html
Labels: feat, 진영🐧

#100 팀원 모집 완료 시 공모전 모집 중인 팀 개수 줄이기
  src/main/java/com/kusithm/meetupd/common/error/ErrorCode.java
  src/main/java/com/kusithm/meetupd/domain/email/service/EmailService.java
  src/main/java/com/kusithm/meetupd/domain/team/controller/TeamController.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/request/RequestChangeRoleDto.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
  src/main/resources/templates/join-team-mail.html
Labels: feat, 진영🐧

#101 등록되지 않은 리뷰가 있는지 확인하기
  src/main/java/com/kusithm/meetupd/domain/review/controller/ReviewController.java
  src/main/java/com/kusithm/meetupd/domain/review/dto/response/CheckUserNotReviewTeamResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/review/mongo/WaitReviewRepository.java
  src/main/java/com/kusithm/meetupd/domain/review/service/ReviewService.java
  src/main/resources/templates/new-review-mail.html
Labels: feat, 진영🐧

#104 공모전 지원 날짜 지난 팀 진행상황 변경 스케줄러
  src/main/java/com/kusithm/meetupd/domain/contest/mongo/ContestRepository.java
  src/main/java/com/kusithm/meetupd/domain/contest/service/ContestService.java
  src/main/java/com/kusithm/meetupd/domain/team/entity/TeamProgressType.java
  src/main/java/com/kusithm/meetupd/domain/team/scheduler/TeamScheduler.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
Labels: feat, 진영🐧

#105 [feat]활동했던 팀 조회 api
  src/main/java/com/kusithm/meetupd/domain/team/dto/TeamIOpenedResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/TeamIWorkedResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/TeamIappliedResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
Labels: feat, 민정🦫

#112 [feat] 팀 관리하러 가기 페이지 api
  src/main/java/com/kusithm/meetupd/domain/team/controller/TeamController.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/TeamManageResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
Labels: feat, 민정🦫

#114 [fix] 팀 오픈하기 공모전별로 하나만 가능하도록 수정
  src/main/java/com/kusithm/meetupd/common/error/ErrorCode.java
  src/main/java/com/kusithm/meetupd/domain/team/mysql/TeamUserRepository.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
Labels: fix, 민정🦫

#115 [fix] 팀,팀원 최근 모집순으로 정렬되도록 수정
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
Labels: fix, 민정🦫

#117 [fix] 모집 현황 인원수 집계 수정
  src/main/java/com/kusithm/meetupd/domain/team/dto/request/TeamProceedResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/RecruitingContestTeamResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/TeamDetailResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/TeamIappliedResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
Labels: fix, 민정🦫

#118 [fix] 해당 공모전에서 모집중인 팀 리스트 모집 인원수 집계 수정
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/RecruitingContestTeamResponseDto.java
Labels: fix, 민정🦫

#123 [refactor] 프론트 요청으로 RecruitingTeamResponseDto에 teamId 추가
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/RecruitingTeamResponseDto.java
Labels: refactor, 민정🦫

#121 팀 활동 모집 완료 건너뛰고 팀 활동 중으로 변경
  src/main/java/com/kusithm/meetupd/domain/team/scheduler/TeamScheduler.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
Labels: fix, 진영🐧

#125 팀 유저의 역할을 제대로 비교하지 못하던 문제 해결
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
Labels: fix, 진영🐧

#129 [refactor] 프론트 요청으로 내가 오픈한 팀 api에 contestId 추가
  src/main/java/com/kusithm/meetupd/domain/team/dto/TeamIOpenedResponseDto.java
Labels: refactor, 민정🦫

#130 [refactor] 팀 지원 로직 수정
  src/main/java/com/kusithm/meetupd/domain/team/controller/TeamController.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/request/ApplyTeamRequestDto.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
Labels: refactor, 민정🦫

#132 [refactor] 활동중인 팀 페이지 합류한 팀원 팀장 포함 집계로 수정
  src/main/java/com/kusithm/meetupd/domain/team/dto/request/TeamProceedResponseDto.java
Labels: refactor, 민정🦫

#136 리뷰 남길 때 해당 팀에 이미 리뷰 남겼으면 실패되도록 검증
  src/main/java/com/kusithm/meetupd/common/error/ErrorCode.java
  src/main/java/com/kusithm/meetupd/domain/review/aws/AWSFeignClient.java
  src/main/java/com/kusithm/meetupd/domain/review/aws/dto/request/SendEmailByAWSFeignRequestDto.java
  src/main/java/com/kusithm/meetupd/domain/review/service/ReviewService.java
Labels: feat, 진영🐧

#140 불필요 import 제거
  src/main/java/com/kusithm/meetupd/common/config/SecurityConfig.java
  src/main/java/com/kusithm/meetupd/common/error/dto/ErrorResponse.java
  src/main/java/com/kusithm/meetupd/common/jwt/TokenProvider.java
  src/main/java/com/kusithm/meetupd/domain/contest/controller/ContestController.java
  src/main/java/com/kusithm/meetupd/domain/contest/dto/response/FindContestsResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/contest/entity/Contest.java
  src/main/java/com/kusithm/meetupd/domain/contest/service/ContestService.java
  src/main/java/com/kusithm/meetupd/domain/email/service/EmailService.java
  src/main/java/com/kusithm/meetupd/domain/fileUpload/controller/S3FileUploadController.java
  src/main/java/com/kusithm/meetupd/domain/fileUpload/dto/response/FileUploadResponse.java
  src/main/java/com/kusithm/meetupd/domain/fileUpload/service/AwsS3Service.java
  src/main/java/com/kusithm/meetupd/domain/review/dto/request/NonUserReviewRequestDto.java
  src/main/java/com/kusithm/meetupd/domain/review/entity/UserReviewedTeam.java
  src/main/java/com/kusithm/meetupd/domain/review/entity/inner/SelectKeyword.java
  src/main/java/com/kusithm/meetupd/domain/review/entity/inner/SelectTeamCulture.java
  src/main/java/com/kusithm/meetupd/domain/review/mongo/NonUserReviewRepository.java
  src/main/java/com/kusithm/meetupd/domain/review/mysql/UserReviewedTeamRepository.java
  src/main/java/com/kusithm/meetupd/domain/sample/controller/SampleController.java
  src/main/java/com/kusithm/meetupd/domain/sample/dto/request/CreateSampleRequestDto.java
  src/main/java/com/kusithm/meetupd/domain/sample/dto/response/CreateSampleResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/sample/entity/Sample.java
  src/main/java/com/kusithm/meetupd/domain/sample/mysql/SampleRepository.java
  src/main/java/com/kusithm/meetupd/domain/sample/service/SampleService.java
  src/main/java/com/kusithm/meetupd/domain/team/controller/TeamController.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/TeamIOpenedResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/request/PageDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/request/TeamProceedResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/PageResponseDTO.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/RecruitingContestTeamResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/RecruitingTeamResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/TeamDetailResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/TeamIappliedResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/team/entity/Team.java
  src/main/java/com/kusithm/meetupd/domain/team/entity/TeamLocation.java
  src/main/java/com/kusithm/meetupd/domain/team/mysql/TeamUserRepository.java
  src/main/java/com/kusithm/meetupd/domain/team/scheduler/TeamScheduler.java
  src/main/java/com/kusithm/meetupd/domain/team/service/TeamService.java
  src/main/java/com/kusithm/meetupd/domain/user/controller/UserController.java
  src/main/java/com/kusithm/meetupd/domain/user/dto/UserMypageResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/user/dto/response/ReviewPageUserResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/user/dto/response/UserReviewResponseDto.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/LocationType.java
  src/main/java/com/kusithm/meetupd/domain/user/entity/User.java
  src/main/java/com/kusithm/meetupd/domain/user/mysql/UserTicketSpendRepository.java
  src/main/java/com/kusithm/meetupd/domain/user/service/UserService.java
Labels: remove, 진영🐧

#141 [refactor] 해당 공모전에서 모집중인 팀 리스트 모집현황 수정
  src/main/java/com/kusithm/meetupd/domain/team/dto/response/RecruitingContestTeamResponseDto.java
Labels: feat, 민정🦫
